name: draftguru
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - fastapi[standard]
  - sqlmodel
  - pydantic-settings
  - psycopg
  - asyncpg
  - alembic
  - beautifulsoup4
  - pip
  - pandas
  - pip:
      - -e .[dev]
